apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-clicker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-clicker
  template:
    metadata:
      labels:
        app: demo-clicker
    spec:
      containers:
      - name: demo-clicker
        image: demo-clicker:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 998
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /count
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo-clicker
spec:
  selector:
    app: demo-clicker
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
