apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-clicker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-clicker
  template:
    metadata:
      labels:
        app: demo-clicker
    spec:
      containers:
      - name: demo-clicker
        image: demo-clicker:v1
        ports:
        - containerPort: 8080  # application port
          name: http
        - containerPort: 8081  # management/health port
          name: management
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        env:
        - name: MANAGEMENT_SERVER_PORT
          value: "8081"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "never"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
# Main application service
apiVersion: v1
kind: Service
metadata:
  name: demo-clicker
spec:
  selector:
    app: demo-clicker
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
# Management service (cluster-internal only)
apiVersion: v1
kind: Service
metadata:
  name: demo-clicker-management
spec:
  selector:
    app: demo-clicker
  ports:
  - port: 8081
    targetPort: 8081
    name: management
  type: ClusterIP
